name: pythongis

channels:
  - conda-forge

dependencies:
  - python=3.11.5
  - contextily=1.3.0
  - fiona=1.8.22
  - folium=0.14.0
  - geojson=3.0.1
  - geopandas=1.0.1
  - geoplot=0.5.1
  - geopy=2.4.0
  - hvplot=0.8.4
  - ipykernel=6.25.2
  - ipython=8.15.0
  - jupyterlab=4.0.6
  - jupyter-sphinx=0.4.0
  - matplotlib=3.8.0
  - myst-nb=0.17.2
  - nbsphinx=0.9.3
  - openjdk=20.0.2
  - openpyxl=3.1.2
  - osmnx=1.6.0
  - owslib=0.29.2
  - pygeos=0.14
  - pykrige=1.7.0
  - pyrosm=0.6.2
  - pysal=23.1
  - r5py=0.1.1
  - r5py.sampledata.helsinki>=0.1.1dev2
  - r5py.sampledata.sao_paulo>=0.1.1dev2
  - rasterio=1.3.7
  - rasterstats=0.19.0
  - scipy=1.11.3
  - seaborn=0.12.2
  - shapely=2.0.1
  - sphinx=5.0.2
  - sphinx-book-theme=1.0.1
  - sphinxcontrib-bibtex=2.5.0
  - xarray=2023.9.0
  - xarray_leaflet=0.2.3
  - xarray-spatial=0.3.5
  
  # Packages from PyPi
  - pip=23.2.1
  - pip:
    - geodatasets==2023.3.0
    - jupyterlab_myst==2.1.0
